mathiasbynens/regexpu-core

.editorconfig
.travis.yml
README.md
package.json
property-escapes.md
rewrite-pattern.js
scripts/character-class-escape-sets.js
scripts/iu-mappings.js
tests/tests.js

There is no spec yet. https://github.com/mathiasbynens/es-unicode-regexp-proposal/issues/2 has a bunch of info and links.
I’d like to implement support for a minimal version of `\p{…}` and `\P{…}` to get a better sense of what to spec + edge cases.
This issue is blocked by:

Add experimental support for Unicode property escapes (`\p{…}` and `\P{…}`)

---

rewrite-pattern.js
tests/tests.js

Only capturing groups update the group index

---

rewrite-pattern.js
tests/tests.js

In this PR we decouple the regjsparser switch from the regexpu-core transformer switch. It is a breaking change since it does not throw for `\\p{Unified_Ideograph}` when `unicodePropertyEscape` is not enabled, instead it assumes our user know exactly what she is doing and only transform the features as instructed.
By doing this, `babel-preset-env` can have more granular control on ES6+ regex features. For example, when user specifies
```json
{
"target": "Hypothetical browser supports unicode property escape but not named capturing groups"
}
```
and let's say the pattern we want to transform is `/(?<name>\p{Unified_Ideograph}{3})/u` we don't have to transform unicode property escape here and instead should only pass `namedGroup: true`. 
```js
rewritePattern( …
```

breaking: decouple parser switch and transformer switch

---

rewrite-pattern.js
tests/tests.js

In this PR we introduce `useDotAllFlag` to instruct that the `/s` flag is used in the transpiled result, which mean `dot` can skip transpilation when `useDotAllFlag: true` is specified.
The typical use case is that the user would like to preserve `/s` flag while transforming the other features:
```js
rewritePattern('<(?<tag>\d)+>.*?<\/\k<tag>>', 'su', {
'namedGroup': true
})
// returns (incorrect due to dotAll is not respected)
// <([0-9])+>[\0-\t\x0B\f\x0E-\u{2027}\u{202A}-\u{10FFFF}]*?<\/\1>
rewritePattern('<(?<tag>\d)+>.*?<\/\k<tag>>', 'su', {
'namedGroup': true,
'dotAllFlag': true,
})
// returns (correct but suboptimal)
// <([0-9])+>[\0-\u{10FFFF}]*?<\/\1>
rewritePattern('<(?<tag>\d)+>.*?<\/\k<tag>>', 'su', {
'namedGroup': true,
'useDotAllFlag': true,
})
// expected (the dot transform …
```

support useDotAllFlag

---

package.json
rewrite-pattern.js
tests/tests.js

This allows us to take advantage of the browser's natrual case folding for `i` flag.
Fixes #45

Implement negative character classes with a negative lookahead

---

README.md
demo.js
rewrite-pattern.js
tests/tests.js

The more we move into the future, the less users will need to compile old regular expression features. However, configuring _regexpu-core_ to only compile some specific features is quite hard. This proposal aims to simplify how the options behave and interact.
---
Every new syntax feature could be handled in three possible ways:
1. Compile it to older syntax
2. Parse it and leave it as-is
3. Don't parse it (throw an error)
Currently, every regexp feature is supported in a different way:
- `u` is (1) by default, and `useUnicodeFlag` makes it (2)
- `s` is (1) by default, but _regexpu-core_ respects the `s` flag only if `dotAllFlag` is set. `useDotAllFlag` makes it (2).
- `\p{...}` is (2) by default (if the `u` flag is enabled), and `unicodePropertyEscape` makes it (1)
- Named groups are (3) …

[breaking] Change the API to choose which features to compile

---

README.md
demo.js
package.json
rewrite-pattern.js
tests/tests.js

This adds support for `&&` and `||`. It doesn't support string alternatives in sets (`[\q{ab|cd}]`) or the updates to `\p`: I'll open other PRs for them.
I'm marking this as a wip because:

Implement support for `&&` and `||` in `v` sets

---

demo.js
rewrite-pattern.js
tests/tests.js

This PR introduces support for `\q{...}` in `v` sets.
Depens on #52 (the first commit is part of that PR; only review the second one)

Support strings in sets in `v` mode

---

demo.js
package.json
rewrite-pattern.js
tests/tests.js

All the new files in `data/` are generated by `scripts/sequence-properties.js`.
I coped the list of properties from Table 69 of https://arai-a.github.io/ecma262-compare/?pr=2418, is it correct?

Add support for `\p` Unicode properties of strings

---

.github/workflows/main.yml
rewrite-pattern.js

I'm sorry, I know that this is annoying. Babel 7 still supports Node.js 6, which is painful but we don't want to drop it until the next major (Babel 8 will only support Node.js 12+, or Node.js 14+).
`regexpu-core` is _almost_ compatible with Node.js 6, except for an ES2017 trailing comma I introduced in one of my recent pull requests. This PR makes it work again, and adds a small test (it just runs `demo.js`, because mocha requires a newer Node.js version) to make sure that we don't accidentally use unsupported syntax.

Ensure Node.js 6 compatibility

---

README.md
rewrite-pattern.js
tests/tests.js

This commit relaxes duplicate named groups checks to implement https://github.com/tc39/proposal-duplicate-named-capturing-groups.

Allow duplicate group names in alternatives

---

rewrite-pattern.js
tests/tests.js

Fixes #59 
The names tracking logic was only enabled when transforming named groups; this commit always enables it. I suggest reviewing [without whitespace changes](https://github.com/mathiasbynens/regexpu-core/pull/67/files?w=1), since many changes are just indentation.

Fix parsing of named refs when not transforming named groups

---

package.json
rewrite-pattern.js
tests/tests.js

Fixes https://github.com/mathiasbynens/regexpu-core/issues/72
Fixes https://github.com/babel/babel/issues/15357
This is a regression introduced in #46. 
- Add basic astral handling for `/[^a-z]/u`, previously the astral characters are matched as surrogates (https://github.com/babel/babel/issues/15357)
- Resort to the previous negative set approach when the `i` flag is not enabled (https://github.com/babel/babel/issues/15357)
<s>Pending https://github.com/mathiasbynens/regexpu-fixtures/pull/3</s>

fix: astral handling on character class negation

---

.github/workflows/main.yml
.github/workflows/publish-on-tag.yml
package.json
scripts/iu-mappings.js
tests/tests.js

Migrated to the builtin node test runner so that we have less dev deps to care about.
<s>This PR contains commits from #81 which fixed the CI error. Please review the last commit only.</s>

Update test infra

---

rewrite-pattern.js

Enable the `unicodeSetsFlag` parsing as it is included in the ES2024.
This PR is a breaking change.
Migration: If you are using the `"unicodeSetsFlag": "parse"` option, simply remove it as the parse utility will be always enabled.

Always enable unicodeSetsFlag parsing

---

rewrite-pattern.js
tests/fixtures/character-class.js
tests/fixtures/unicode-set.js
tests/fixtures/unicode.js
tests/tests.js

In this PR we reuse the unicode fixtures for the v-flag tests, based the observation that `/.../u` and `/.../v` should yield the same result unless set/string properties features are involved.
We also introduce the `matches` and `nonMatches` properties to the v-flag fixture runner: They includes the strings that the transpiled regex is supposed to match / reject. It is useful when the transpiled regex is too verbose for proper comprehension.
<s>This PR includes commits from #84, I will rebase once that PR is merged.</s>
<s>This is a draft PR as I still haven't figured out how to avoid double-bmpify regex strings: In the negative set notation we extract single code points from the `UNICODE_SET`, which yields surrogate stuffs in the output, but then it was bmp-ified again in the …

Fix v-flag bugs

---

rewrite-pattern.js
tests/tests.js

In this PR we skip the `processItem` when it is a `symbol`-kind and has code point within ASCII range.
This fix will prevent `-` transpiled as `\\x2D` when it is not in character class. Besides that, it should speed up a little bit since ASCII symbols are pretty common.

fix: skip ascii symbol in process

---

rewrite-pattern.js
tests/fixtures/character-class.js
tests/fixtures/unicode-set.js
tests/fixtures/unicode.js
tests/tests.js

Fix invert astral capture regression

---

package.json

This PR is based on https://github.com/mathiasbynens/regexpu-core/pull/92, otherwise CI will be failing due to Unicode 16 changes in our depending packages.
This PR should unblock Babel upgrading `regexpu-core` to 6.

Bump regjsparser

---

rewrite-pattern.js
tests/fixtures/modifiers.js
tests/tests.js

Fixes #96.
In this PR we also pack `caseFold` parameters into a bit array avoid per-character queries to these parameters.

Apply case expansion to unicode property escapes within `i` modifier

---

README.md
rewrite-pattern.js
tests/fixtures/modifiers.js
tests/tests.js

The modifiers proposal has reached Stage 4 in the Oct 2024 meeting. Here we silently ignored the `modifiers: "parse"` option, this feature will be always parsed.

always enable modifiers parsing
